### ISSUE TITLE
:latest version appears to produce 15.2 not 15.3?

### ISSUE THREAD

**Issue by apiszcz** [ivanlonel/postgis-with-extensions#21]
Tried a pull, and i see 15.2 not 15.3? Is there something i can change get the 15.3?

docker run -e POSTGRES_PASSWORD=test -d ivanlonel/postgis-with-extensions
docker exec -it 33c20da142e8 bash

postgres=# select version();

PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20
210110, 64-bit

**Comment by ivanlonel** [comment]
Hey @apiszcz

15.3 isn't out yet. The current release of Postgres is 15.2.

Tag labels for this image follow the pattern `X-Y.Z`, where `X` is the *major* Postgres version (starting from version 12) and `Y.Z` is the *major.minor* Postgis version.

So, by saying the `latest` tag currently corresponds to `15-3.3`, I mean Postgresql 15 and Postgis 3.3.

Which specific minor version of Postgres is used depends on [upstream](https://github.com/postgis/docker-postgis), but they also only specify the major version. So the minor Postgres version in this image should always be the most recent available. At least after GitHub runs the next update workflow, on mondays.
